#.github/actions/docker-action/action.yml
name: "Docker Build and Push"

inputs:
  aws_region:
    description: "AWS Region being targeted."
    default: "us-east-1"
    required: true
  role_to_assume:
    description: "Role to assume when interacting with AWS."
    required: true
  image_name:
    description: "Name of the image to build"
    default: "base"
    required: true
  image_tag:
    description: "Tag of the image to build"
    default: "latest"
    required: true
  context:
    description: "Context of the image to build"
    default: "."
    required: true
  dockerfile:
    description: "Dockerfile to use for the image"
    default: "./Dockerfile"
    required: true
  
runs:
  using: "composite"
  
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    #----------------------------------------------
    # ----- Authenticate With AWS assume role -----
    #----------------------------------------------
    - name: GitHub OIDC Auth to assume AWS Role
      uses: aws-actions/configure-aws-credentials@master
      with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: no

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        driver: docker
    
    #----------------------------------------------
    # -----  Login to AWS ECR  -----
    #----------------------------------------------
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    #----------------------------------------------
    # -----  Build Docker Image  -----
    #----------------------------------------------
    - name: Build Docker Image
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        builder: ${{ steps.buildx.outputs.name }}
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}

    # ----------------------------------------------
    # -----  Push Docker Image to ECR  -----
    # ----------------------------------------------
    - name: Push Docker Image
      id: docker-push
      run: docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
      shell: bash